### ISSUE TITLE
Toward a plugin on QGIS repository

### ISSUE THREAD

**Issue by mbrasebin** [IGNF/NeatMap#3]
Hello in order to make a qgis plugin :

1. Please check that your plugin: 
- [x] has no malicious code
- [x] goes to the appropriate menu (Vector, Raster, Web, Database)
- [x] has at least minimal documentation
- [x] does not duplicate of existing functionalities or plugin, unless there is a good reason
- [x] has a proper license
- [x] does not contain architecture-dependant binaries
- [x] supports English language
- [x] provides a minimal data set for testing **=> Si c'est sur le site de documentation, ça ira ?**
- [x]  has (in the metadata) a link to the code repository and to a bug tracking system of your choice (you can use github or other infrastructures) **=> il faudra mettre à jour lorsque le repo sera déplacé**
- [x] is of reasonable size (try to keep it small, and not exceed 10 Mb)
- [x] english language is used in code (comments, identifiers)
- [x] source repository is in good shape:
     - [x] no generated file is left in repository (ui_*.py, resources_rc.py, gen. help files…)
     - [x] good code organization (subfolders) => **c'est pas le cas, mais les autres font pareil donc ce n'est pas grave ?**
     - [x]  code comments are available
     - [x] PEP8 & Python/QGIS guidelines compliance
     - [x] a README file and a LICENCE file (GPL2 or later mandatory) are present
     - [x]  the licence is compliant wrt external dependencies (e.g. no import of proprietary python module)
   - [x] does not break any other licence (e.g. for data providers, etc.)  or do any illegal thing
    - [x] more info about licencing in our blog post
    - [x] if the plugin has a need for external dependency, this it should be clearly stated in the About metadata field
    - [x] if some dependencies are not available in OSGeo4w Python, a clear indication of how to install them should be given => **Normally, it is automatic, but I added a line on the readme.md**
    - [x] the name of the plugin and the folder name do not repeat the word `plugin`
    - [x] they plugins should make use of QgsNetworkAccessManager instead of home brew urllib2/requests/... solutions, which most of the times do not make use of proxy settings => **https://github.com/julienperret/NeatMap/blob/e99ef4478c9c0ff6ac58e101d1cf795998f51cff/classification.py il y a une installation avec pip au début de ce code mais, c'est bon ?**
    - [x] finally, the use of plugin builder plugin is recommended, especially for new users.

2. Go to [QGIS plugin repo](https://plugins.qgis.org/plugins/) and click on Share a plugin.

**Comment by julienperret** [comment]
Pour moi, tout est bon pour la première version.
