### ISSUE TITLE
Enabling travis to build and test the project

### ISSUE THREAD

**Issue by mbrasebin** [IGNF/NeatMap#7]
Hello,

I do not have the right access to add this project to travis builds. Is it possible to add it ?

Mickaël

**Comment by julienperret** [comment]
Done.

**Comment by mbrasebin** [comment]
I replay the travis script in a 16.04 Ubuntu VM without error.

**Comment by mbrasebin** [comment]
The error is further now : 

https://travis-ci.org/IGNF/NeatMap/jobs/484415602

This commit seems to help :

https://github.com/IGNF/NeatMap/commit/3c6287be706594f77a5c558c39b8117a4fac1e34

**Comment by mbrasebin** [comment]
@julienperret  : the new error seems to be this one : https://github.com/openmole/openmole/issues/223 ?

Did you find a solution ?

**Comment by mbrasebin** [comment]
Solved with xvfb, new error Segmentation fault (core dumped) https://travis-ci.org/IGNF/NeatMap/builds/484480504?utm_medium=notification&utm_source=email

**Comment by mbrasebin** [comment]
Posted an issue here : https://gis.stackexchange.com/questions/310110/pyqgis-3-4-4-segmentation-fault-error

**Comment by mbrasebin** [comment]
It is solved, the project can compile now. I close this issue, there is one last problem about the install and the use of sklearn in a same function (cf the other issue)
